//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSHRCA.BusinessLogic.DataModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabinet
    {
        public Cabinet()
        {
            this.GDCabinets = new HashSet<GDCabinet>();
        }
    
        public int Id { get; set; }
        public int Code { get; set; }
    
        public virtual ICollection<GDCabinet> GDCabinets { get; set; }
    }
}
