//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSHRCA.BusinessLogic.DataModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDTeacher
    {
        public int Id { get; set; }
        public int GroupDisciplineId { get; set; }
        public int TeacherId { get; set; }
        public int ActualHoursNumber { get; set; }
        public int InitialHoursNumber { get; set; }
        public int LessonTypeId { get; set; }
    
        public virtual GroupDiscipline GroupDiscipline { get; set; }
        public virtual LessonType LessonType { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
