//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSHRCA.BusinessLogic.DataModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupDisciplines = new HashSet<GroupDiscipline>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int PeopleCount { get; set; }
        public int CuratorId { get; set; }
    
        public virtual ICollection<GroupDiscipline> GroupDisciplines { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
