//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSHRCA.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupDiscipline
    {
        public GroupDiscipline()
        {
            this.GDCabinets = new HashSet<GDCabinet>();
            this.GDCabinets1 = new HashSet<GDCabinet>();
            this.GDTeachers = new HashSet<GDTeacher>();
        }
    
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int DisciplineId { get; set; }
    
        public virtual AcademicDiscipline AcademicDiscipline { get; set; }
        public virtual ICollection<GDCabinet> GDCabinets { get; set; }
        public virtual ICollection<GDCabinet> GDCabinets1 { get; set; }
        public virtual ICollection<GDTeacher> GDTeachers { get; set; }
        public virtual Group Group { get; set; }
    }
}
